### ISSUE TITLE
People can exploit the TCC Compendium book

### ISSUE THREAD

**Issue by barraIhsan** [CreeperMagnet/the-creepers-code#87]
So my friend is spamming the command to give the compendium book. And then because the compendium book data is very large. I got like banned forever because whenever I join, my player data become too big. And I got kicked. My friend is also spamming the book in the chest so you cannot open the chest again (if you open it, you'll be kicked).

I think I know a way to fix it :
1. Give it a delay
So like maybe 10 minutes / 1 day delay

2. Clear the book when the player has 2 or more

3. Add a `blacklist.tcc.compendium` tags.
So maybe you add a tag that will prevent people to run the command (`@a[tag=!blacklist.tcc.compendium`)

**Comment by CreeperMagnet** [comment]
This is working as intended. Get better friends.

In order to stack that many compendiums, you would have to purposely throw them out of your inventory onto the ground and continue to spam the command, since running the command **already** clears you of existing compendiums.

I will add the ban tag, but this is most certainly more of a problem with your friends being assholes than it is with my code being broken.

**Comment by JC1OZ** [comment]
> This is working as intended. Get better friends.
> 
> In order to stack that many compendiums, you would have to purposely throw them out of your inventory onto the ground and continue to spam the command, since running the command **already** clears you of existing compendiums.
> 
> I will add the ban tag, but this is most certainly more of a problem with your friends being assholes than it is with my code being broken.

lol

**Comment by DaveHue1** [comment]
Imagine having friends smh

**Comment by CreeperMagnet** [comment]
Fixed by adding a `tcc.compendium_ban` tag. But you should still get less shitty friends.

**Comment by barraIhsan** [comment]
Ok, lmao
